version: '3.5'

services:

 web:
  build:
   context: app
   dockerfile: Dockerfile
  depends_on:
   - db
  command: bash -c "python -u data_test_migrate.py && python -u app.py"
  env_file: development.env
  networks:
   - default
  ports:
   - "5000:5000"
  volumes:
   - ./app:/app

 db:
  image: mongo:latest
  hostname: mongodb
  environment:
    - MONGO_INITDB_DATABASE=posterr
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - .:/src/core/infra/database
  ports:
    - "27017:27017"

networks:
 default:
  driver: bridge

volumes:
 appdata:
  driver: local
 mongodbdata:
  driver: local